name: Deploy to VPS on Push

on:
  push:
    branches:
      - main # ou master, selon ton repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to VPS and pull latest code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/FXServer/server-data/resources/[local]/fivem-test
            git pull origin main
